- name: Install other tools (tmux, fzf, rg, etc.)
  become: true
  ansible.builtin.apt:
    name:
      - tmux
      - tmuxp
      - fzf
      - ripgrep
      - fd-find
      - zoxide
      - xclip
      - git-absorb
      - pipx
      - autopoint  # for fswatch
      - texinfo  # for fswatch
    state: latest

- name: Add fd alias
  ansible.builtin.file:
    path: "{{lookup('env', 'HOME')}}/.local/bin/fd"
    src: "/usr/bin/fdfind"
    state: link

# pipx
- name: Check pipx
  ansible.builtin.shell: command -v pipx
  register: pipx_exists
  ignore_errors: true

# - name: Pipx setup (1/2)
#   when: pipx_exists is failed
#   ansible.builtin.shell: pipx ensurepath

# AWS cli
- name: Check AWS CLI
  ansible.builtin.shell: command -v aws
  register: aws_exists
  ignore_errors: true

- name: Download AWS CLI installer
  when: aws_exists is failed
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: Unarchive AWS CLI installer
  when: aws_exists is failed
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/

- name: Install AWS CLI
  become: true
  when: aws_exists is failed
  ansible.builtin.shell: /tmp/aws/install

# bottom
- name: Check for bottom
  ansible.builtin.shell: command -v btm
  register: bottom_exists
  ignore_errors: true

- name: Download bottom deb
  when: bottom_exists is failed
  ansible.builtin.get_url:
    url: https://github.com/ClementTsang/bottom/releases/download/{{bottom_version | default('0.9.1')}}/bottom_{{bottom_version | default('0.9.1')}}_amd64.deb
    dest: /tmp/bottom.deb

- name: Install bottom deb
  become: true
  when: bottom_exists is failed
  ansible.builtin.shell: dpkg -i /tmp/bottom.deb

# lazydocker
- name: Check for lazydocker
  ansible.builtin.shell: command -v lazydocker
  register: lazydocker_exists
  ignore_errors: true

- name: Install lazydocker
  when: lazydocker_exists
  ansible.builtin.shell: go install github.com/jesseduffield/lazydocker@latest

# fswatch
- name: Check if fswatch is installed
  shell: "command -v fswatch"
  register: fswatch_installed
  ignore_errors: true

- name: Clone fswatch
  when: fswatch_installed is failed
  ansible.builtin.git:
    force: true
    repo: https://github.com/emcrisostomo/fswatch
    dest: "{{lookup('env', 'HOME')}}/tools/fswatch"

- name: Configure, build, and install fswatch
  when: fswatch_installed is failed
  become: true
  ansible.builtin.shell: >-
    cd {{lookup('env', 'HOME')}}/tools/fswatch && 
    ./autogen.sh && ./configure && make && make install
