- name: Install other tools (tmux, fzf, rg, etc.)
  become: true
  ansible.builtin.apt:
    name:
      - tmux
      - tmuxp
      - fzf
      - ripgrep
      - fd-find
      - zoxide
      - xclip
      - git-absorb
    state: latest

- name: Add fd alias
  ansible.builtin.file:
    path: "{{lookup('env', 'HOME')}}/.local/bin/fd"
    src: "/usr/bin/fdfind"
    state: link

# AWS cli
- name: Check AWS CLI
  ansible.builtin.shell: command -v aws
  register: aws_exists
  ignore_errors: true

- name: Download AWS CLI installer
  when: aws_exists is failed
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: Unarchive AWS CLI installer
  when: aws_exists is failed
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/

- name: Install AWS CLI
  become: true
  when: aws_exists is failed
  ansible.builtin.shell: /tmp/aws/install

# bottom
- name: Check for bottom
  ansible.builtin.shell: command -v btm
  register: bottom_exists
  ignore_errors: true

- name: Download bottom deb
  when: bottom_exists is failed
  ansible.builtin.get_url:
    url: https://github.com/ClementTsang/bottom/releases/download/{{bottom_version | default('0.9.1')}}/bottom_{{bottom_version | default('0.9.1')}}_amd64.deb
    dest: /tmp/bottom.deb

- name: Install bottom deb
  become: true
  when: bottom_exists is failed
  ansible.builtin.shell: dpkg -i /tmp/bottom.deb

# lazydocker
- name: Check for lazydocker
  ansible.builtin.shell: command -v lazydocker
  register: lazydocker_exists
  ignore_errors: true

- name: Install lazydocker
  when: lazydocker_exists
  ansible.builtin.shell: go install github.com/jesseduffield/lazydocker@latest

