---
- name: Test playbooks
  hosts: localhost

  pre_tasks:
    - name: Update repositories
      become: true
      ansible.builtin.apt:
        update_cache: yes
      changed_when: False

  vars:
    golang_version: "1.20.4"
    hack_version: "3.003"
    nerd_symbols_version: "3.2.1"
    bottom_version: "0.9.1"

  # TODO: validate that the playbook is not being ran as root
  tasks:
    - name: Setup core components
      ansible.builtin.include_tasks: "tasks/core.yaml"

    - name: Install Rust
      ansible.builtin.include_tasks: "tasks/rust.yaml"

    - name: Install Golang
      ansible.builtin.include_tasks: "tasks/go.yaml"

    - name: Install Node
      ansible.builtin.include_tasks: "tasks/npm.yaml"

    - name: Install Starship
      ansible.builtin.include_tasks: "tasks/starship.yaml"

    - name: Install zsh
      ansible.builtin.include_tasks: "tasks/zsh.yaml"

    - name: Install fonts
      ansible.builtin.include_tasks: "tasks/fonts.yaml"

    - name: Install kitty
      ansible.builtin.include_tasks: "tasks/kitty.yaml"

    - name: Install additional tooling
      ansible.builtin.include_tasks: "tasks/tools.yaml"

    - name: Install docker
      ansible.builtin.include_tasks: "tasks/docker.yaml"

    - name: Build neovim nightly
      ansible.builtin.include_tasks: "tasks/neovim_nightly.yaml"
      tags:
        - nightly
